<?php
	function get_home(){
		$home="";
		$server = $_SERVER['SERVER_NAME'];
		$self = $_SERVER['PHP_SELF']; 
		$self = explode("/", $self);
		if($server==="localhost")
			$home = "http://". $server . "/". $self[1];
		else
			$home = "http://". $server;
		return $home;
	}

	function get_email_body($invitee, $event){
		$link = get_home();
		$link.="/rsvp.php?request=email_link&attendeeId={$invitee->attendeeId}";    
		
		$body ="";
			
			$img_src = 'http://23.235.211.204/~shakirs/email_banner.png';
			$body ="<body style='margin: 10px;'>";
			$body.="<div style='width: 640px; font-family: Arial, Helvetica, sans-serif; font-size: 12px;'>";
			$body.="<div align='center'><img src='{$img_src}'></div><br />";
			
			$body.="<div style='margin:10px;'>";
			$body.="<br />";
			if(isset($invitee->attendeeName))
				$body.="Dear {$invitee->attendeeName},<br />";
			else            
				$body.="Dear User,<br />";  
			$body.="<br />";
			
			$body.="You are cordially invited to attend the following event:<br />";
			$body.="Event:<strong>{$event->eventTitle}</strong>.<br />";
			$body.="Date:<strong>{$event->eventDate}</strong>.<br />";		
			$body.="Location:<strong>{$event->eventLocation}</strong>.<br />";		
			$body.="Starts at:<strong>{$event->eventStartTime}</strong>.<br />";
			$body.="Ends at:<strong>{$event->eventEndTime}</strong>.<br />";
			$body.="Further Details:<strong><a href='{$link}'>Click here</a></strong>.<br />";		
			
			if ($invitee->attendeeName != ''){
			$body.="<br /><strong>Additional Note:</strong><br />";
			$body.="{$invitee->additionalNote}";
			}
			
			$body.="<br />";
			$body.="<br />";		
			$body.="<br />Your attendee reference code is: <strong>{$invitee->attendeeRefCode}</strong>";
			$body.="<br />You will need this code at the time of checkin.";
			$body.="<br />";
			$body.="Please RSVP by clicking on the link below :";
			$body.="<br /><br /><a href='{$link}' target='blank'>";
			$body.="{$link}</a><br />";
			$body.="<br />";
			$body.="Thank you.<br />";
			$body.="<br />";
			$body.="Sincerely, <br />";
			$body.="Invitations Team,<br />";
			$body.="Evently - The complete event management solution<br />";
			$body.="wwww.event.ly<br />";
			$body.="<br /><br /><br /><br />";
			$body.="This email was intended for {$invitee->attendeeEmailAddress}<br />";
			$body.="If you are receiving this email by error, or you have not sent a password reset request, Kindly ignore this email<br />";
			$body.="Thankyou.<br />";
			$body.="</div>";
			$body.="</div>";
			$body.="</body>";    
		
		return $body;
	}

	function send_email($from, $fromName, $to, $toName, $subject, $body, $nonhtmlbody)
	{
		
		require_once("includes/phpmailer/class.phpmailer.php");
		
		$mail = new PHPMailer();
		
		$server = $_SERVER['SERVER_NAME'];
		if($server==="localhost"){    
		$mail->IsSMTP(); // set mailer to use SMTP
		$mail->Host = "ssl://smtp.gmail.com";
		$mail->Port = 465;
		$mail->SMTPAuth = true;     // turn on SMTP authentication
		//$mail->Username = "themilestone01@gmail.com";  // SMTP username
		//$mail->Password = "xcbndryjojecjlzv"; // SMTP password        
		$mail->Username = "shakir.shabbir52@gmail.com";  // SMTP username
		$mail->Password = "cqcbriatgtftqrmt"; // SMTP password        	
		/*
			This pass code was generated by google security authentication and instructed by Anas
		*/
		}
		$mail->From = $from;
		$mail->FromName = $fromName;
		$mail->AddAddress($to, $toName);
		$mail->WordWrap = 50;    // set word wrap            
		$mail->IsHTML(true);    // set email format to HTML
		$mail->Subject = $subject;
		$mail->Body = $body;
		$mail->AltBody = "This is the body in plain text for non-HTML mail clients";        
		$result = $mail->Send(); // send message		
		return $result;
	}
?>